import { IVacationRequest } from "@/components/company/table/VacationColumns";

export const DUMMY_VACATION_REQUESTS: IVacationRequest[] = [
  {
    id: 1,
    requestType: "연차",
    requester: "김철수",
    requestDate: "2025.04.01 ~ 2025.04.03",
    reason: "가족 행사",
    status: "대기중",
  },
  {
    id: 2,
    requestType: "반차",
    requester: "이영희",
    requestDate: "2025.04.05",
    reason: "감기",
    status: "승인",
  },
  {
    id: 3,
    requestType: "특별",
    requester: "박민수",
    requestDate: "2025.04.07 ~ 2025.04.10",
    reason: "개인 사정",
    status: "거절",
  },
  {
    id: 4,
    requestType: "병가",
    requester: "최수진",
    requestDate: "2025.04.11",
    reason: "독감",
    status: "대기중",
  },
  {
    id: 5,
    requestType: "연차",
    requester: "김영호",
    requestDate: "2025.04.15 ~ 2025.04.16",
    reason: "가족 여행",
    status: "대기중",
  },
  {
    id: 6,
    requestType: "출산휴가",
    requester: "박선영",
    requestDate: "2025.04.20 ~ 2025.04.27",
    reason: "출산 예정",
    status: "승인",
  },
  {
    id: 7,
    requestType: "반차",
    requester: "이정훈",
    requestDate: "2025.04.18",
    reason: "병원 방문",
    status: "승인",
  },
  {
    id: 8,
    requestType: "특별",
    requester: "송지현",
    requestDate: "2025.04.25 ~ 2025.04.26",
    reason: "남아프리카 공화국 해외 출장 / 부산 출장",
    status: "거절",
  },
  {
    id: 9,
    requestType: "연차",
    requester: "한도윤",
    requestDate: "2025.04.29",
    reason: "개인 사정",
    status: "거절",
  },
  {
    id: 10,
    requestType: "연차",
    requester: "한도윤",
    requestDate: "2025.04.29",
    reason: "개인 사정",
    status: "거절",
  },
  {
    id: 11,
    requestType: "연차",
    requester: "한도윤",
    requestDate: "2025.04.29",
    reason: "개인 사정",
    status: "거절",
  },
  {
    id: 12,
    requestType: "연차",
    requester: "한도윤",
    requestDate: "2025.04.29",
    reason: "개인 사정",
    status: "거절",
  },
  {
    id: 13,
    requestType: "연차",
    requester: "한도윤",
    requestDate: "2025.04.29",
    reason: "개인 사정",
    status: "거절",
  },
  {
    id: 14,
    requestType: "연차",
    requester: "한도윤",
    requestDate: "2025.04.29",
    reason: "개인 사정",
    status: "거절",
  },
  {
    id: 15,
    requestType: "연차",
    requester: "한도윤",
    requestDate: "2025.04.29",
    reason: "개인 사정",
    status: "거절",
  },
];
